#!/usr/bin/env bash
set -e

setup_ssh_directory() {
  export SSH_DIR=$HOME/.ssh
  sudo mkdir -p $SSH_DIR
}

check_file_exists() {
  if [[ ! -f $1 ]]; then
    echo -e "\e[0;31mError: File $1 does not exist.\e[0m"
    exit 1
  fi
}

copy_keys() {
  check_file_exists "$HOME/id_ed25519_agenix.pub"
  check_file_exists "$HOME/id_ed25519_agenix"
  cp $HOME/id_ed25519_agenix.pub $SSH_DIR
  cp $HOME/id_ed25519_agenix $SSH_DIR
  chmod 600 $SSH_DIR/id_ed25519_{agenix,agenix.pub}
  echo -e "\e[0;32mKeys copied successfully.\e[0m"
}

set_keys() {
  check_file_exists "$HOME/id_ed25519.pub"
  check_file_exists "$HOME/id_ed25519"
  cp $HOME/id_ed25519.pub $SSH_DIR/id_ed25519.pub
  cp $HOME/id_ed25519 $SSH_DIR/id_ed25519
  chmod 600 $SSH_DIR/id_ed25519
  chmod 644 $SSH_DIR/id_ed25519.pub
}

change_ownership() {
  sudo chown $USER:wheel $SSH_DIR/id_ed25519{,.pub}
  sudo chown $USER:wheel $SSH_DIR/id_ed25519_{agenix,agenix.pub}
}

setup_ssh_directory
copy_keys
set_keys
change_ownership
